apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-operator
    spec:
      containers:
      - name: mysql-operator
        image: mattalord/mysql-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
